### ISSUE TITLE
Greetings

### ISSUE THREAD

**Issue by dzarda** [dmitrystu/libusb_stm32#109]
Hello Dmitry

If you're in Mosc w I fear that soon we may not be able to communicate. I'm thinking all I can what can be done to help achieve peace in u.k r and big help would be communication which is becoming harder due to the fire wal being built up. I want to try to convey my deepest sorrow about the invsn of u.k r which is now a major w a r instigated by r u with soon tens of thousand r u and u.k r ded.

The prepostrous pretext that the w. e s t is turning nzi, broadcasted by your tv, makes me shiver. I fear that with the events like r u firing on the np plant will lead to major suffering for all.

Please let me know what you think.

Jaroslav

**Comment by dmitrystu** [comment]
IMO this is not a place for the politic talks. I don't support the war at all and want it to be stopped. This is my point.
