### ISSUE TITLE
with pedantic, this two places wont compile

### ISSUE THREAD

**Issue by aneox** [dmitrystu/libusb_stm32#133]
https://github.com/dmitrystu/libusb_stm32/blob/343a4740688fc1f036591a2e9cabfac49b2f4540/src/usbd_stm32f105_otgfs.c#L418 
 is here fall to default normal? if ok, it must be comment here // fall through, for gcc

https://github.com/dmitrystu/libusb_stm32/blob/343a4740688fc1f036591a2e9cabfac49b2f4540/src/usbd_stm32f105_otgfs.c#L439

in this line,  error: ISO C forbids 'return' with expression, in function returning void [-Werror=pedantic], so just remove return word

https://github.com/dmitrystu/libusb_stm32/blob/343a4740688fc1f036591a2e9cabfac49b2f4540/src/usbd_stm32f105_otgfs.c#L337

possible bug, error: 'tmp' may be used uninitialized in this function [-Werror=maybe-uninitialized]

**Comment by dmitrystu** [comment]
Sorry for the late reply. Now i have a some time to continue maintaining this project.
