### ISSUE TITLE
How do I un-stall to send data out?

### ISSUE THREAD

**Issue by jcw** [dmitrystu/libusb_stm32#21]
I'm trying to write a serial console layer. When the host sends data, all is well, the device receives it and processes it. After that, it enters NAK state, as I understand it. Both endpoints are stalled.

But what if the device wants to send data in this state? How do I get the device to start sending, i.e. report to the host that it has data to send? The `ep_setstall()` function appears to be for internal use.

**Comment by jcw** [comment]
Thanks for the explanation and pointer, Dmitry. Much appreciated.

**Comment by jcw** [comment]
FWIW, I have a terminal app reading on the host side at all times. The only way I found to unblock is:

    EP_TX_VALID(EPR(CDC_TXD_EP));

I do this when the first console output char is stored in my buffer, on the assumption that a poll to the USB driver in the near future will then trigger an endpoint callback on TX to send that buffer. I had to disable double-buffering for this to work on F103, btw.

It sort-of-works, I can see console output in my terminal. There is some duplicate data, i.e. fragments getting sent twice, perhaps the EP_TX_VALID() call can't be made at arbitrary times.

I wonder if console output could be written directly into the PMA area, with periodic unblocking of the IN(TX) side when there is data to send.

**Comment by dmitrystu** [comment]
AFAIK the transmitted data not erased from PMA buffer on TX transaction. So if you set TX endpoint to ACK (VALID) state without new data the old data will be transferred. So what do you want to do ? Is it will some sort of console-controlled device like modem ? I think for this you needs two different buffers. One for input stream (commands and data from host) and one for output stream (answers, echo for commands, data from device to host e.t.c) And two different callbacks of course.
The loopback is very simple, all data that comes from host will be send back without any processing.
Hmmm... It must be a good idea for another cdc-based example.

**Comment by jcw** [comment]
Ah, of course - I shouldn't set VALID before the PMA buffer has been updated.

What I'm after is a serial device which can act as console/debug for a µC, more or less as a drop-in replacement for a UART. Indeed, two separate buffers, and corresponding RX and TX callbacks. To make things simple, at least for now, the RX buffer is exactly 64 bytes and only filled when completely empty, and the TX buffer is 63 bytes, so it can always be sent out in its entirety.

I'm writing this in C++, but basically, the API is:

```
bool writable () { return txFill < sizeof txBuf; }
void putc (int c) { while (!writable()) poll(); txBuf[txFill++] = c; }
bool readable () { return rxNext < rxFill; }
int getc () ( while (!readable()) poll(); return rxBuf[rxNext++]; }
```

Both `putc` and `getc` are blocking, but that can be avoided by checking `writable` or `readable`.

**Comment by dmitrystu** [comment]
I think you can use usd_poll() with callbacks to manage transfer between buffers and USB host and getc() and putc() to pop and push data from/to buffers. In case of empty RX buffer EOF can be returned

**Comment by jcw** [comment]
This seems to work, I had not realised that `ep_write` will do the right thing when IN(TX) is busy:

    bool writable () {
        poll();
        return txFill < sizeof txBuf;
    }
    void putc (int c) {
        while (!writable())
            flush();
        txBuf[txFill++] = c;
    }
    bool readable () {
        poll();
        return rxNext < rxFill;
    }
    int getc () {
        while (!readable()) ;
        return rxBuf[rxNext++];
    }
    void flush () {
        if (txFill > 0) {
            while (ep_write(CDC_TXD_EP, txBuf, txFill) != txFill)
                poll();
            txFill = 0;
        }
    }

Again, many thanks for your help.
