### ISSUE TITLE
STM32F070

### ISSUE THREAD

**Issue by microwavesafe** [dmitrystu/libusb_stm32#29]
I've successfully used this library with stm32f401re and now I'm trying to get it to work with stm32f070rb. Looking at the datasheet the register names, bits and memory locations are identical to the stm32l052, so that code should work, but it fails to set up the address in the initial step. If I compile the same code for the stm32f401re it works, so I'm pretty sure I have my descriptors set up.

I've set the GPIO to high speed, but it didn't help. I'm getting this error back under Linux. 

``device descriptor read/64, error -71``
``Device not responding to setup address.``

Flash DFU bootloader is working, so it's not hardware and I was wondering if anyone had an example of it working on this device?

**Comment by microwavesafe** [comment]
I found the problem, it was simple in the end. I hadn't turned on the USB clock in RCC->CFGR3. Should this be something that the library takes care of for this processor?

**Comment by microwavesafe** [comment]
I was wondering if this should be added to usbd_stm32l052_devfs.c > enable(). As this takes care of all the other RCC configurations?

**Comment by microwavesafe** [comment]
I have created a CDC example, it enumerates as a serial device and creates a ttyACM0 device file. I can connect to it with a serial terminal and I can send data to the serial terminal from the device, but I don't get an interrupt when I send data back from the serial terminal to the device. Same code runs fine on the stm32f401re device.

Does anyone know of a setting that prevents the CTR interrupts firing?

**Comment by microwavesafe** [comment]
I have now compiled your demo for this device and it gives the same results. The USB enumerates correctly, the serial terminal connects (I also see an increase in frames on the DM / DP lines when the terminal is connected, but I'm not sure what they are) but I don't receive any data. I'm guessing the endpoints aren't set up correctly?

**Comment by microwavesafe** [comment]
To finish up a long day of debug. It looks like the problem was with my optimisation of endpoint configurations for the 401 device. I think i'm right in saying the 401 has 3 bidirectional endpoints, whereas the 070 has 8 unidirectional endpoints.

So my first mistake was to use the same endpoint number for both directions for the 070 (0x01 for RX and 0x81 for TX). My second mistake was to only call usbd_reg_endpoint on the RX endpoint. This worked for the 401, because they were the same endpoint number.

**Comment by dmitrystu** [comment]
I have checked RM0360 reference manual for F070. The F070 USBFS machine looks like as in L052. RCC: 48Mhz USB PHY clock control is it's switchable between HSI48(default) and PLL for L052 and fixed on PLL for F070 PLL, but requires to enable it.
Endpoints. L052 machine uses 8 universal endpoints which can be used in bidirectional single buffered or unidirectional double buffered modes. So you can use both 0x01 and 0x81 addresses for one physical endpoint but in single-buffered mode only (control, single-buffered bulk or interrupt). F401 has dedicated control endpoint 0, 3 dedicated TX endpoints with dedicated configurable FIFOs and 3 dedicated RX endpoints with single shared FIFO. There is no special "double-buffered" feature for F401. It's depends on the FIFO size.

**Comment by dmitrystu** [comment]
USB_EPTYPE_DBLBUF flag for OTGFS machines just doubles TX FIFO size for TX endpoints. Shared RX FIFO size is fixed and can be adjusted by MAX_RX_PACKET preprocessor variable (128 by default)

**Comment by microwavesafe** [comment]
Thank you for the clarifying the details. I was finding it difficult to compare the differences in amongst all the detail.

I am using double buffering, so using different endpoint number for the two difference architectures is fine. The reason I came unstuck is the HID / CDC combination descriptor I wrote for the F401 used all the endpoints so I had to use them as bi-directional.
