### ISSUE TITLE
Using the demo source code in CubeIDE

### ISSUE THREAD

**Issue by mne1991** [dmitrystu/libusb_stm32#42]
Hello,

may I ask you if it is possible to show how to load the demo source code (for example of F429) into a STM32CubeIDE project (or to upload the final project of this IDE)? I tried doing that by myself for a long time but I could not get functional code.

More specifically, I am using the Discovery Board of STM32F429 MCU (where the USB connection is done by HS-IN-FS).

Regards

**Comment by dmitrystu** [comment]
Sorry, I have no great experience with Stm32Cube/SystemWorkbench for STM32 as with other Eclipse-based IDE's.

**Comment by dmitrystu** [comment]
Check this SystemWorkbench project. [demo project for NUCLEO-F429ZI](https://ufile.io/hrghcbl6) I think it may help you.
