### ISSUE TITLE
Why I need two interface for acm?

### ISSUE THREAD

**Issue by mttbx** [dmitrystu/libusb_stm32#67]
This is not a bug report. I'm newbie to USB driver. I tried your demo, and I found there's two interfaces to support acm. And the endpoint of the first interface wasn't registered (CDC_NTF_EP). I noticed that you grouped these two interfaces together (USB_DTYPE_INTERFASEASSOC), why did you do that? Can you help me out?

**Comment by dmitrystu** [comment]
Hi.
This for the generic CDC driver under Windows. See [MS Docs](https://docs.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-interface-association-descriptorl)

**Comment by mttbx** [comment]
Thanks
