### ISSUE TITLE
STM32F303xC AF for PA11 and PA12

### ISSUE THREAD

**Issue by aam335** [dmitrystu/libusb_stm32#71]
Same problem as STM32F373xC. Possibly all "C" has same "feature".

**Comment by dmitrystu** [comment]
Fortunately, this is **documented** right, at least in the *DocID026415 Rev 5* (F303D/E Datasheet) and *DS9118 Rev 14* (F303B/C Datasheet).
But in the *DocID022691 Rev 7* (F373xx Datasheet) the USB pins defined as Additional Function for the PA11 and PA12, but in fact, it's an Alternate function 14. I have found this by tracing an internal bootloader.
