### ISSUE TITLE
Any porting guide?

### ISSUE THREAD

**Issue by vakochetkov** [dmitrystu/libusb_stm32#75]
I appreciate devfs approach to split MCU dependant driver and usbd core. 
But I would like to port/fork/extend this library to Milandr MCUs.
Are there any porting guide or any other docs to build devfs, for example, 1986VE92 (replacement for F103 but it has it's own peripherals, including usb)? Any tricks&tips? 
p.s. It's pretty cool such amazing library are written by russian programmer ^)

**Comment by dmitrystu** [comment]
Hi.
Send me PM

**Comment by vakochetkov** [comment]
Sent e-mail
